namespace: proj

backend:
  name: proj-backend
  image:
    repository: studentbatchacr.azurecr.io/proj-backend
    tag: 10
    pullPolicy: IfNotPresent
  replicaCount: 1
  containerPort: 4000
  service:
    port: 4000
    targetPort: 4000
   

frontend:
  name: proj-frontend
  image:
    repository: studentbatchacr.azurecr.io/proj-frontend
    #tag: v1
    tag: 10
    pullPolicy: IfNotPresent
  replicaCount: 1
  containerPort: 80
  service:
    port: 80
    targetPort: 80
  