apiVersion: v1
kind: Service
metadata:
  name: proj-frontend-service
  namespace: proj
spec:
  type: NodePort
  selector:
    app: proj-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31157